# Generated by Django 3.0.8 on 2020-07-14 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='timestamp',
            new_name='timeStamp',
        ),
    ]
